// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpAG0rsHnY-sLakFC2nKxgPEsse7_w-2E',
    appId: '1:454971816334:web:3b1949f99aa73b4a2b4cdf',
    messagingSenderId: '454971816334',
    projectId: 'winperax-83187',
    authDomain: 'winperax-83187.firebaseapp.com',
    storageBucket: 'winperax-83187.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6y8xyGrb3o3g2UTzAvUbZ1s8ENVpxok4',
    appId: '1:454971816334:android:6488e3051031d2132b4cdf',
    messagingSenderId: '454971816334',
    projectId: 'winperax-83187',
    storageBucket: 'winperax-83187.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDpAG0rsHnY-sLakFC2nKxgPEsse7_w-2E',
    appId: '1:454971816334:web:3b1949f99aa73b4a2b4cdf',
    messagingSenderId: '454971816334',
    projectId: 'winperax-83187',
    authDomain: 'winperax-83187.firebaseapp.com',
    storageBucket: 'winperax-83187.firebasestorage.app',
  );
}
